# Permalinks
permalink:        /blog/:categories/:year/:title

# Site-wide settings
encoding:         utf-8
timezone:         Europe/London

# Set a default template for blogs so I don't have to
defaults:
 -
  scope:
    path: 		  "" # empty string for all files
  values:
    layout:       "post"
    card:         true

kramdown:
  input:          GFM
  hard_wrap:      false

sass:
  sass_dir:       _scss

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Setup
title:            Martin Steel
description:      The ramblings of a Manchester based .NET developer
url:              http://www.martinsteel.co.uk
paginate:         5
paginate_path:    "/page/:num"
baseurl:          ""

author:
  name:           Martin Steel
  email:          martin@martinsteel.co.uk
  twitter:        martin_steel

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/martinsteel/martinsteel.github.io


