# Permalinks
permalink:        /blog/:categories/:year/:title

# Site-wide settings
encoding:         utf-8
timezone:         Europe/London

# Set a default template for blogs so I don't have to
defaults:
 -
  scope:
    path: 		  "" # empty string for all files
  values:
    layout:       "post"
    card:         true

kramdown:
  input:          GFM
  hard_wrap:      false

sass:
  sass_dir:       _scss

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

# Setup
title:            Martin Steel
tagline:          The ramblings of a Manchester based .NET developer
url:              http://martinsteel.co.uk
paginate:         5
paginate_path:    "/page/:num"
baseurl:          /
author:
  name:           Martin Steel
  url:            https://twitter.com/martin_steel
  email:          martin@martinsteel.co.uk

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/martinsteel/martinsteel.github.io


