# Permalinks
permalink:        /blog/:categories/:year/:title
relative_permalinks: true

# Site-wide settings
encoding:         utf-8
timezone:         Europe/London

# Set a default template for blogs so I don't have to
defaults:
 -
  scope:
    path: 		  "" # empty string for all files
  values:
    layout:       "post"

# Setup
title:            Martin Steel
tagline:          The ramblings of a .NET developer
url:              http://martinsteel.co.uk
paginate:         1
paginate_path:    "/blog/page/:num"
baseurl:          /
author:
  name:           Martin Steel
  url:            https://twitter.com/martin_steel
  email:          martin@martinsteel.co.uk

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/martinsteel/martinsteel.github.io


